Inject memset
sysprog21/rv32emu pull request #196
Opened 2023-08-24 06:57 UTC by qwe661234

1. Because RISC-V use jal instruction as function call, so we remove recursive jump tranlation to detect function call.
2. To identify memset, we analyze the pattern of the first basic block of memset for comparison. If the basic block aligns with the pattern, we extract the instruction sequence starting from the initial PC of the basic block and then compare it with the pre-recorded memset instruction sequence. Upon detecting a memset, we substitute the basic block with the standard library function memset.

Based on performance results below, we gain 3% performance improvement when running coreMark and lost 1% performance when running dhrysone. The performance impact is resulted in the number of invoking memset times.

* Intel Core i7-11700

|   Metric   |origin|proposed |Speedup|memset invoke|
| -------- | -------- | -------- | -------- |-------- |  
| Dhrystone  | 2293.25    | 2267.00| -1% |4|
| CoreMark   | 1881.410     | 1933.813| +3%|3124365|

see: #153

2023-08-24 07:16 UTC, jserv commented on src/emulate.c
> +    uint32_t memset_insn[] = {
Append the corresponding assembly as inlined comments for reference purpose.

2023-08-24 07:16 UTC, jserv commented on src/emulate.c
> +    uint32_t memset_insn[] = {
Add `static const` qualifier for `memset_insn`.

2023-08-24 07:29 UTC, jserv commented on src/emulate.c
> +bool parse_memset(riscv_t *rv)
Add `static` qualifier.

2023-08-24 08:24 UTC, jserv commented on src/emulate.c
> +    for (int i = 0; i < 55; i++) {
It seems that both prologue and epilogue are included in the above sequence, right?

2023-08-24 08:38 UTC, jserv commented on src/emulate.c
> +    for (int i = 0; i < 55; i++) {
`memcmp` provided by glibc or other C runtimes is usually optimized for modern microprocessors, and it can be much faster than simple iterations. Do you have any idea to utilize `memcmp`?

2023-08-24 08:39 UTC, jserv requested changes
Add memcpy substitution as well. Applications such as Doom can benefit.

2023-08-24 08:40 UTC, jserv commented on src/emulate.c
> +            if (ir->imm == 15 && ir->rd == 6 && ir->rs1 == 0) {
Add more comments.

2023-08-24 20:35 UTC, jserv commented on src/emulate.c
> +static bool parse_memset(riscv_t *rv)
The function name should be `detect_memset`.

2023-08-24 20:35 UTC, jserv commented on src/emulate.c
> +static bool parse_memcpy(riscv_t *rv)
Ditto. Should be `detect_memcpy`.

2023-08-25 00:48 UTC, jserv commented
f a certain region is recognized as containing a sequence of known `memset` or `memcpy` instructions, is it possible to replace the invocation of such a region? In other words, instead of replacing the region with a faster alternative, can we directly modify the instructions on the caller's side?

2023-08-25 19:20 UTC, jserv commented
Rather than identifying `memcpy` / `memset` during the execution phase, I am considering whether it might be more feasible to detect them during the decoding phase. This approach would involve examining the initial portion of the instruction sequence in the buffer and using `memcmp` to validate, resulting in faster and deterministic instruction substitution.

2023-08-27 13:38 UTC, jserv commented on src/emulate.c
> +static bool parse_memset2(riscv_t *rv)
Should be `detect_memset2`. Of course, it would be better if one routine can manipulate several patterns.

2023-08-27 13:39 UTC, jserv commented on src/emulate.c
> +    for (int i = 0; i < 7; i++) {
Replace the hardcoded `7` with `ARRAYS_SIZE` macro.

2023-08-27 13:39 UTC, jserv commented on src/emulate.c
> +    for (int i = 0; i < 105; i++) {
Ditto. Utilize `ARRAYS_SIZE` macro.

2023-08-28 12:24 UTC, jserv commented on src/emulate.c
> +#define ARRAY_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]))
Don't do that! The macro `ARRAYS_SIZE` is already defined in `src/common.h`.

2023-08-28 14:58 UTC, ChinYikMing commented
To maintain the consistency of accessing riscv's register, I think the code below which `X[1]`, `X[10]`, `X[11]` and `X[12]` can be rewrite with `X[rv_reg_ra]`, `X[rv_reg_a0]`, `X[rv_reg_a1]` and `X[rv_reg_a2]` respectively.

```c
memset((char *) m->mem_base + rv->X[10], rv->X[11], rv->X[12]);
rv->PC = rv->X[1] & ~1U;
```

2023-08-30 06:08 UTC, merged