Use xpack as the GCC toolchain
sysprog21/rv32emu pull request #290
Opened 2023-12-12 20:24 UTC by henrybear327

An experiment of using `xpack` as the GCC toolchain instead of our self-compiled docker image.

#286

2023-12-12 20:25 UTC, henrybear327 commented
Image size evolution (the total size shown is accumulative, with respect to the previously listed items) 

- `Ubuntu:22:04` -> 69.4 MB
- Copying the source code (`tests` folder itself is about 500 MB) ->  831 MB
- Install extra packages (e.g. `libsdl2-dev`) -> 1.49GB

For the GCC toolchain
- Using xpack toolchain -> 3.56GB
- Copying from the self-built GCC image -> 2.12GB

2023-12-18 07:20 UTC, visitorckw commented on Dockerfile
> +    build-essential curl && \
Due to the presence of a git submodule in the source code, it's necessary to install git here in order to successfully execute the subsequent 'RUN make' command.

2023-12-22 08:14 UTC, henrybear327 commented
Using xpack will actually increase the image size, so maybe we should drop this PR in the end.

2023-12-22 08:47 UTC, jserv commented
> Using xpack will actually increase the image size, so maybe we should drop this PR in the end.

The goal here is to utilize scripts for downloading and extracting the toolchain from xpack, similar to those already in use by our CI pipeline. This approach should help in significantly reducing the size of our Docker image.

2023-12-22 08:49 UTC, henrybear327 commented
> > Using xpack will actually increase the image size, so maybe we should drop this PR in the end.
> 
> The goal here is to utilize scripts for downloading and extracting the toolchain from xpack, similar to those already in use by our CI pipeline. This approach should help in significantly reducing the size of our Docker image.

Got it. So the following changes would be made
- add a script that can automatically install the GCC toolchain 
- remove the existing toolchain from the image
- compile the rv32emu and relevant binaries in the intermediate images and copy it to the final image

2023-12-22 08:56 UTC, jserv commented
> Got it. So the following changes would be made
> * add a script that can automatically install the GCC toolchain
> * remove the existing toolchain from the image
> * compile the rv32emu and relevant binaries in the intermediate images and copy it to the final image

Take [run #7295920920](https://github.com/sysprog21/rv32emu/actions/runs/7295920920), for example. It takes over 11 minutes, yet the actual time spent preparing the build environment and launching the build process accounts for only half of this elapsed time.

2024-01-01 11:58 UTC, jserv requested changes
Ensure `git` is installed as a prerequisite; otherwise, you will encounter the following error.

```
 > [linux/amd64 base_gcc 5/6] RUN make:
0.108 Makefile:86: No sdl2-config in $PATH. Check SDL2 installation in advance
0.110 /bin/sh: 1: pkg-config: not found
0.180 Check the file build/.config for configured items.
0.224   CC	build/map.o
0.299   CC	build/utils.o
0.342 git submodule update --init src/softfloat/
0.351 make: git: No such file or directory
0.352 make: *** [Makefile:73: src/softfloat/build/Linux-RISCV-GCC/Makefile] Error 127
```

2024-01-01 13:56 UTC, henrybear327 commented
Added `libsdl2-dev libsdl2-mixer-dev` to the intermediate image, so we can compile a complete `rv32emu` binary. 

Should `libsdl2-dev libsdl2-mixer-dev` also be presented in the final image?

Also, since this dockerfile is not for development anymore (unless I misunderstand the intention of removal of the GCC toolchain), should we just copy the elf files in the build folders, and leave other source files, etc. out?

2024-01-01 14:28 UTC, henrybear327 commented
> CI / host-arm64

It's now the same compile time as `CI / host-arm64` Github CI job, since it's the QEMU emulating arm64 that's slow. 

Image size is now basically 65 MB + size of directories copied in from rv32emu repo

2024-01-01 16:09 UTC, jserv commented
> Should `libsdl2-dev` and `libsdl2-mixer-dev` also be presented in the final image?

No, the Docker image should be limited to only the essential components of rv32emu, excluding SDL display and audio, as these can lead to issues in containerized environments. Therefore, just remove the `libsdl2-dev` and `libsdl2-mixer-dev` packages.

> should we just copy the elf files in the build directory, and leave other source files, etc. out?

Yes, exactly. Users can always view the source code through the GitHub website. Only the built ELF files (for both the host and the RISC-V target) are preserved.

2024-01-01 16:12 UTC, jserv commented
The [recent CI record](https://github.com/sysprog21/rv32emu/actions/runs/7377774989/job/20072140463) indicates that building and publishing a Docker image to Docker Hub requires 8 minutes. It looks pretty well.

2024-01-01 17:36 UTC, jserv requested changes
Drop unnecessary packages such as SDL2.

2024-01-01 18:20 UTC, henrybear327 commented
Updated as requested/discussed.

2024-01-01 19:14 UTC, merged

2024-01-01 19:14 UTC, jserv commented
Thank @henrybear327 for contributing!