Support RV32FC
sysprog21/rv32emu pull request #316
Opened 2024-01-01 17:48 UTC by fourcolor

This patch is aimed at supporting RV32FC-only instructions. The following instructions are implemented in this PR: C.FSW, C.FLW, C.FSWSP, C.FLWSP.

2024-01-01 19:17 UTC, jserv requested changes
Refine the README.md for the corresponding extension description.

2024-01-01 19:20 UTC, jserv requested changes
1. Append `Close #315` at the end of git commit message.
2. Attempt to run the corresponding RISC-V Architectural Tests when possible.

2024-01-01 21:08 UTC, visitorckw commented on src/decode.c
> +/* C.LW: CL-format
"C.LW" should be corrected to "C.FLW".

2024-01-01 21:14 UTC, visitorckw commented
The current [riscv-arch-test](https://github.com/riscv-non-isa/riscv-arch-test) does not include a test suite for RV32FC. However, we could explore using [riscv-ctg](https://github.com/riscv-software-src/riscv-ctg) to generate a suitable test suite.

2024-01-04 15:09 UTC, visitorckw commented
Similar to commit [cfa1c9f](https://github.com/sysprog21/rv32emu/commit/cfa1c9f8a3331eb53239bd284bcf298fab933793),  we need to conduct alignment checks on load/store addresses.

2024-01-04 15:41 UTC, fourcolor commented
After a few days of researching RISC-V-CTG, I consider it is challenging to develop a related test suite in a short period. Therefore, I would like to inquire whether adding a TODO comment in the code or opening an issue, along with explaining in the README that certain parts have not undergone arch-test testing, would be a better practice.

2024-01-05 03:37 UTC, jserv commented
> After a few days of researching [riscv-ctg](https://github.com/riscv-software-src/riscv-ctg), I consider it is challenging to develop a related test suite in a short period.

Rather than expanding existing compilation suites, it would be more effective to develop a straightforward, specialized test program specifically for validating RV32FC support.

2024-01-06 09:30 UTC, fourcolor commented
I ultimately managed to figure out how to use riscv-ctg to generate relevant test suites, and I also added tests for RV32FC in the CI.

2024-01-06 13:52 UTC, visitorckw commented on src/decode.h
> +        )                                              \
Please correct the indentation here.

2024-01-06 14:12 UTC, visitorckw approved these changes

2024-01-06 15:18 UTC, merged

2024-01-06 15:18 UTC, jserv commented
Thank @fourcolor for contributing!