Fix file descriptor resource leaks
sysprog21/rv32emu pull request #327
Opened 2024-01-10 23:28 UTC by henrybear327

2024-01-11 00:16 UTC, henrybear327 commented
Other errors detected by infer

```
src/elf.c:194: error: Uninitialized Value
  `node.right_red` is read without initialization during the call to `map_insert()`. 
  192.     /* initialize the symbol table */
  193.     map_clear(e->symbols);
  194.     map_insert(e->symbols, &(int){0}, &(char *){NULL});
           ^
  195. 
  196.     /* get the string table */

src/jit.c:1535: error: Null Dereference
  `state` could be null (null value originating from line 1534) and is dereferenced. 
  1533. {
  1534.     struct jit_state *state = malloc(sizeof(struct jit_state));
  1535.     state->offset = 0;
            ^
  1536.     state->size = size;
  1537.     state->buf = mmap(0, size, PROT_READ | PROT_WRITE | PROT_EXEC,

src/riscv.c:310: error: Uninitialized Value
  `node.right_red` is read without initialization during the call to `map_insert()`. 
  308.     FILE *files[] = {stdin, stdout, stderr};
  309.     for (size_t i = 0; i < ARRAYS_SIZE(files); i++)
  310.         map_insert(s->fd_map, &i, &files[i]);
               ^
  311. 
  312.     return s;
```

2024-01-11 01:54 UTC, jserv commented
> Other errors detected by infer

Have you been resolving all the errors raised by infer?

2024-01-11 01:57 UTC, jserv commented on src/elf.c
> +        close(fd);
Follow the method used by `cache_create` for employing `goto` to release resources, which results in more concise code.

2024-01-11 01:57 UTC, jserv commented on src/emulate.c
> +    if (out_file_path[0] != '-') {
Remove `{` and `}`.

2024-01-11 06:42 UTC, henrybear327 commented
> > Other errors detected by infer
> 
> Have you been resolving all the errors raised by infer?

I do not understand the first error raised by infer. Can you provide some hints if you have any? 

I will fix the second one by adding necessary NULL checks for `malloc` and `calloc`. 

The third one I actually don't see the issue though. Can you also provide some hints if you have any? 

Thank you!

2024-01-11 07:33 UTC, jserv commented
> I do not understand the first error raised by infer. Can you provide some hints if you have any?

You should check src/map.[ch] instead. Using static analysis is a bit tricky. Sometimes, you just figure out something considered as false alarm.

2024-01-11 07:36 UTC, jserv requested changes
Refine the subject of this issue and git commit messages.

The statement "caught by infer" should only appear in the commit message body rather than the subject.

2024-02-05 14:26 UTC, henrybear327 commented
The only remaining issue lies in the `map.c` code, which I tried to read the RB-tree source code and couldn't quite spot the issue so far. I suggest that we create another issue and debug the potential issue in the RB-tree in a separate PR.

```
src/elf.c:194: error: Uninitialized Value
`node.right_red` is read without initialization during the call to `map_insert()`.
  192.     /* initialize the symbol table */
  193.     map_clear(e->symbols);
  194.     map_insert(e->symbols, &(int){0}, &(char *){NULL});
              ^
  195.
  196.     /* get the string table */

Found 1 issue
    Issue Type(ISSUED_TYPE_ID): # 
    Uninitialized Value(PULSE_UNINITIALIZED_VALUE): 1
```

2024-02-05 15:58 UTC, jserv commented on src/jit.c
> +    assert(state != NULL);
Rewrite as `assert(state)`.

2024-02-05 15:58 UTC, jserv requested changes
Split this pull requests into individual functional ones.

2024-02-05 16:52 UTC, closed without merging

2024-02-05 18:41 UTC, henrybear327 commented
> Split this pull requests into individual functional ones.

Split as requested