End the indirect jump when potential hotspot is detected
sysprog21/rv32emu pull request #371
Opened 2024-03-04 04:15 UTC by qwe661234

Currently, the indirect jump does not switch to T1C when potential hotspot is detected, it would make execution stuck in interpreter mode. This modification make execution end when potential hotspot is detected.

2024-03-04 04:52 UTC, jserv commented
The following code snip appears several times in `src/emulate.c` and `src/rv32_template.c`, and can you unify by jumping the label in `RVOP`?
```c
        rv->csr_cycle = cycle;
        rv->PC = PC;
        return true;
```

2024-03-04 04:54 UTC, qwe661234 commented
> The following code snip appears several times in `src/emulate.c` and `src/rv32_template.c`, and can you unify by jumping the label in `RVOP`?
> 
> ```c
>         rv->csr_cycle = cycle;
>         rv->PC = PC;
>         return true;
> ```

However, since this label is within the scope of a function, I can replace them with a MACRO.

2024-03-04 05:01 UTC, jserv commented
> However, since this label is within the scope of a function, I can replace them with a MACRO.

That sounds good. The label will be named `end_op`. The term "op" (operation) is preferred over "insn" (instruction) to clearly differentiate between RISC-V instructions and the IR operations derived from them. Our interpreter specifically manipulates these IR operations, rather than the direct RISC-V instructions.

2024-03-04 09:17 UTC, jserv commented on src/rv32_template.c
> +#define END_OP             \
This macro should appear in `src/emulate.c`, renamed to `RVOP_END`.

2024-03-04 09:27 UTC, jserv commented on src/emulate.c
> +#define RVOP_END           \
Modify macro `RVOP` to facilitate `RVOP_END`.

2024-03-06 14:52 UTC, jserv requested changes
Rephrase "This modification make execution end when potential hotspot is detected" to
> This revision ensures the execution halts upon identifying a potential hotspot. It aims to make the execution process more efficient by stopping when a significant area of code usage is detected, allowing for targeted optimization.

2024-03-07 08:25 UTC, merged