Introduce Infer static analyzer to the CI pipeline
sysprog21/rv32emu pull request #379
Opened 2024-03-11 07:40 UTC by henrybear327

The [Infer Docker Image](https://hub.docker.com/repository/docker/sysprog21/infer/general) in use is hosted on DockerHub, which was [built and pushed to sysprog21 by us](https://henrybear327.github.io/notes/posts/container/infer/) since [Infer's latest upstream release](https://github.com/facebook/infer/releases/tag/v1.1.0) is very outdated at the time of writing.

The docker image size is around 470 MB, after numerous attempts to reduce its size from 3GB.

This PR also fixes issues reported by Infer. (The value written to `&target_reg` is never used.)

2024-03-11 07:51 UTC, jserv requested changes
Skip Arm64 based host during static analysis.

2024-03-11 07:56 UTC, henrybear327 commented
> Skip Arm64 based host during static analysis.

I am unaware that the Arm64-based host will be run during the static analysis phase, as I didn't specify `arch: aarch64`. Or maybe I am mistaken?

2024-03-11 08:00 UTC, jserv commented
> The docker image size is around 470 MB, after numerous attempts to reduce its size from 3GB.

Can you rebuild Infer static analysis tool with `-Os` set? And then, strip the ELF files accordingly.

2024-03-11 08:11 UTC, henrybear327 commented
> > The docker image size is around 470 MB, after numerous attempts to reduce its size from 3GB.
> 
> Can you rebuild Infer static analysis tool with `-Os` set? And then, strip the ELF files accordingly.

I can give this a try, but I have no guarantee on this.

2024-03-11 09:05 UTC, jserv commented
If Clang scan-build already makes sense to CI, do we need Infer? Can you show the considerations?

2024-03-11 09:44 UTC, jserv commented
The [build-infer.sh](https://github.com/facebook/infer/blob/main/build-infer.sh) invokes `autogen.sh`, which generates GNU Automake style scripts. At the moment, only C and Python are required for static analysis.

Reference: [The Growth of the OCaml Distribution](https://ocamlpro.com/blog/2023_01_02_ocaml_distribution/)

2024-03-11 09:52 UTC, henrybear327 commented
> The [build-infer.sh](https://github.com/facebook/infer/blob/main/build-infer.sh) invokes `autogen.sh`, which generates GNU Automake style scripts. At the moment, only C and Python are required for static analysis.
> 
> Reference: [The Growth of the OCaml Distribution](https://ocamlpro.com/blog/2023_01_02_ocaml_distribution/)

The previous Docker Image contained only C and Python analysis capability, but now with the release build, Java is also included. 

Based on prior experience, Java can be excluded by passing in parameters, but some changes to `create_binary_release.sh` will be required as I am now using [create_binary_release.sh](https://github.com/facebook/infer/blob/main/scripts/create_binary_release.sh) to build a standalone binary instead of invoking `build-infer.sh` directly like before.

2024-03-12 02:48 UTC, jserv commented on .github/workflows/main.yml
> +  static-analysis-infer:
Don't create a new entry. Use the existing one instead.

2024-05-21 20:45 UTC, closed without merging

2024-05-21 20:47 UTC, henrybear327 commented
The infer image pipeline broke recently (node11 now has strict internet bandwidth restrictions), and the effort to maintain an image is a bit cumbersome. Thus, closing this PR for now.