Support hosting WebAssembly demo page locally
sysprog21/rv32emu pull request #413
Opened 2024-04-08 10:57 UTC by ChinYikMing

To enhance the user experience of using WebAssembly version of rv32emu, we shall provide a Makefile target (serve-wasm) to serve the WebAssembly demo page in an easy way.

Since rv32emu leverages TCO (tail call optimization) when being compiled, so we have to tell if the user's browser supports TCO. Currently, only Chrome with MAJOR 112 and Firefox with MAJOR 121 supports TCO execution runtime, thus we focus on this two browsers. Also, use color text to remind the users if they need to update their Chrome or Firefox.

See also: #75

2024-04-08 11:01 UTC, jserv commented on mk/color.mk
> +YELLOW=\033[0;33m
It is not worthy to create a new file containing only 3 lines. Move these to `mk/common.mk`.

2024-04-08 11:02 UTC, jserv requested changes
Move WebAssembly related rules to `mk/wasm.mk`.

2024-04-08 11:40 UTC, ChinYikMing commented
Run `make serve-wasm CC=emcc` to test it.

Note that you should install emcc then source your emcc firstly. In macOS or Linux, use `source ~/emsdk/emsdk_env.sh`.

2024-04-08 11:42 UTC, ChinYikMing commented
> Move WebAssembly related rules to `mk/wasm.mk`.

Done.

2024-04-08 11:43 UTC, ChinYikMing commented
README will be updated on next.

2024-04-08 12:09 UTC, jserv commented on mk/wasm.mk
> +serve-wasm: $(BIN) check-demo-dir-exist
Rename the target to `start-web`.

2024-04-09 03:41 UTC, jserv requested changes
Update `README.md` to reflect the proposed changes.

2024-04-09 05:29 UTC, ChinYikMing commented
> Update `README.md` to reflect the proposed changes.

Done.

2024-04-09 05:29 UTC, jserv commented on README.md
> +click the Run button to run it.
Mention the demo page as the alternative solution.

2024-04-09 05:29 UTC, jserv commented on README.md
> +`rv32emu` relies on Emscripten to be compiled to WebAssembly. Thus, the target system should have
Put the hyperlink to Emscripten in the first sentence.

2024-04-09 06:26 UTC, merged

2024-04-09 06:26 UTC, jserv commented
Thank @ChinYikMing for contributing!