Fix benchmark CI pipeline
sysprog21/rv32emu pull request #460
Opened 2024-06-16 20:09 UTC by henrybear327

Recompile `dhrystone.elf` and `coremark.elf` in order to fix the benchmark CI pipeline, as discussed at https://github.com/sysprog21/rv32emu/issues/455#issuecomment-2163491139

References:
- https://github.com/sysprog21/rv32emu/issues/451
- https://github.com/sysprog21/rv32emu/issues/455

2024-06-16 20:11 UTC, jserv reviewed
<!-- github-benchmark-action-comment(start): Benchmarks Summary -->
# Benchmarks

<details>

| Benchmark suite | Current: c72230f7e1568e019dbb20aa308c2217ef091793 | Previous: 7a68a6ce80a673e4d87b8586d9770a56b1ed470f | Ratio |
|-|-|-|-|
| `Dhrystone` | `3.44` Average DMIPS over 10 runs | `7.11` Average DMIPS over 10 runs | `2.07` |
| `Coremark` | `0.004` Average iterations/sec over 10 runs | `0.004` Average iterations/sec over 10 runs | `1` |

</details>

This comment was automatically generated by [workflow](https://github.com/sysprog21/rv32emu/actions?query=workflow%3ABenchmark) using [github-action-benchmark](https://github.com/marketplace/actions/continuous-benchmark).
<!-- github-benchmark-action-comment(end): Benchmarks Summary -->

2024-06-16 20:13 UTC, henrybear327 commented
@jserv do you still have the documentation/Makefile/etc. for compiling `coremark.elf`?

2024-06-17 02:47 UTC, jserv requested changes
Strip the prebuilt CoreMark and Dhrystone ELF files.

2024-06-17 04:25 UTC, jserv commented
> do you still have the documentation/Makefile/etc. for compiling `coremark.elf`?

Run `git log build/coremark.elf` to figure out the steps to rebuild CoreMark.

2024-07-03 22:50 UTC, henrybear327 commented
> > do you still have the documentation/Makefile/etc. for compiling `coremark.elf`?
> 
> Run `git log build/coremark.elf` to figure out the steps to rebuild CoreMark.

Replaced `coremark` using binaries compiled from `rv32emu-prebuilt`

2024-07-03 22:51 UTC, henrybear327 commented
@jserv The performance is still slow after replacing both binaries (using the ones compiled from `rv32emu-prebuilt`)

2024-07-03 22:54 UTC, jserv commented
> @jserv The performance is still slow after replacing both binaries (using the ones compiled from `rv32emu-prebuilt`)

@vacantron, Can you check?

2024-07-04 00:38 UTC, henrybear327 commented
I tried to compile `rv32emu` locally (`make ENABLE_SDL=0`) and force the benchmark CI to use that binary for execution. 

The DMIPS would be back to normal (see [log](https://github.com/henrybear327/rv32emu/actions/runs/9786597065/job/27021748648), but CoreMark will crash. 

So I think there are 2 issues to investigate
- why is the `make` on CI producing binaries that is super slow somehow?
- why is CoreMark crashing with the locally compiled binary

FYI, the compiler I am using locally is 
```
➜  rv32emu git:(ci/fix_benchmark_pipeline) ✗ gcc --version
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

2024-07-04 01:08 UTC, henrybear327 commented
Things are getting weird... 

Please see this [log](https://github.com/henrybear327/rv32emu/actions/runs/9786807640/job/27022298145). 

If I install `SDL` libraries as shown [here](https://github.com/henrybear327/rv32emu/actions/runs/9786807640/workflow#L15), the DMIPS performance will be back to normal but CoreMark will fail.

2024-07-08 20:50 UTC, henrybear327 commented
Due to GitHub CI pipeline security protection (it's my guess), my latest changes aren't visible here. Please check https://github.com/henrybear327/rv32emu/pull/5. 

@vacantron thanks for providing the arguments to be used for coremark execution! Though I am not sure of the root cause of this error when executing Coremark, cc @jserv 
```
rv32emu: src/emulate.c:632: block_translate: Assertion `prev_ir' failed.
Aborted (core dumped)
Start Test CoreMark benchmark
Traceback (most recent call last):
  File "/home/runner/work/rv32emu/rv32emu/tests/coremark.py", line 16, in <module>
    comp_proc = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'build/rv32emu build/coremark.elf 0x0 0x0 0x66 60000 7 1 [20](https://github.com/henrybear327/rv32emu/actions/runs/9846674893/job/27184952365?pr=5#step:5:21)00' returned non-zero exit status 134.
Traceback (most recent call last):
  File "/home/runner/work/rv32emu/rv32emu/tests/bench-aggregator.py", line 25, in <module>
    run_benchmark(b)
  File "/home/runner/work/rv32emu/rv32emu/tests/bench-aggregator.py", line 13, in run_benchmark
    subprocess.run(args=[interp, b], shell=False, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 5[26](https://github.com/henrybear327/rv32emu/actions/runs/9846674893/job/27184952365?pr=5#step:5:27), in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', 'tests/coremark.py']' returned non-zero exit status 1.
```

 Regarding Dhrystone, that DMIPS value is now reported normally!

2024-07-08 23:45 UTC, vacantron commented
> Though I am not sure of the root cause of this error when executing Coremark

The Coremark with `rv32imafc` extension should work normally now. It seems there are some problems with the certain extension combination.

2024-07-09 01:09 UTC, jserv commented on .github/workflows/benchmark-new.yml
> +    runs-on: ubuntu-22.04
Let's move to Ubuntu 24.04 and drop SDL packages.

2024-07-09 01:10 UTC, jserv requested changes
It is confusing to have `benchmark.yml` and `benchmark-new.yml`.

2024-07-09 13:40 UTC, henrybear327 commented
> It is confusing to have `benchmark.yml` and `benchmark-new.yml`.

Synced offline with @jserv, this is a temporary testing method. 

A new discovery is that if I move the benchmark pipeline to `main.yml`, the latest changes on the pipeline can be reflected directly with the PR. 

I currently have no explanation for this, but to speed up development I will keep the benchmark pipeline in `main.yml` for now.

2024-07-09 13:47 UTC, jserv commented
> I currently have no explanation for this, but to speed up development I will keep the benchmark pipeline in `main.yml` for now.

It sounds acceptable. Let's get the benchark work again.

2024-07-09 16:11 UTC, henrybear327 commented
Good news! The pipeline is finally back online with normal numbers again! Coremark is currently compiled using `rv32imafc` and it can execute without failure, thanks to @vacantron for the suggestion!

@jserv do you happen to remember what were the parameters you used for Coremark? It's not found within the [past commit messages](https://github.com/sysprog21/rv32emu/commits/master/build/coremark.elf) but we would need to supply this in the benchmark script. Currently, the CI is using `0x0 0x0 0x66 30000 7 1 2000` (>= 15000 iterations should be more than 10s of execution time)

Thank you!

2024-07-09 16:29 UTC, henrybear327 commented
> > Though I am not sure of the root cause of this error when executing Coremark
> 
> The Coremark with `rv32imafc` extension should work normally now. It seems there are some problems with the certain extension combination.

I have tried `rv32im` (https://github.com/sysprog21/rv32emu/commits/master/build/coremark.elf), also works!

2024-07-09 16:43 UTC, jserv commented
> do you happen to remember what were the parameters you used for Coremark? It's not found within the [past commit messages](https://github.com/sysprog21/rv32emu/commits/master/build/coremark.elf) but we would need to supply this in the benchmark script. Currently, the CI is using `0x0 0x0 0x66 30000 7 1 2000` (>= 15000 iterations should be more than 10s of execution time)

Prior to this pull request, there was no parameter passing to CoreMark.

2024-07-09 19:28 UTC, henrybear327 commented
> > do you happen to remember what were the parameters you used for Coremark? It's not found within the [past commit messages](https://github.com/sysprog21/rv32emu/commits/master/build/coremark.elf) but we would need to supply this in the benchmark script. Currently, the CI is using `0x0 0x0 0x66 30000 7 1 2000` (>= 15000 iterations should be more than 10s of execution time)
> 
> Prior to this pull request, there was no parameter passing to CoreMark.

I took the arguments from https://github.com/HidetaroTanaka/coremark/blob/main/Makefile#L103 and https://github.com/HidetaroTanaka/coremark/blob/main/Makefile#L107. 

According to the experiment, executing coremark for 1 second can perform around 1200 iterations. Also, if the execution time is less than 10s, coremark will fail with a non-zero exit code. So I set the iteration to 20000 for now.

2024-07-09 19:36 UTC, henrybear327 commented
Known issues:
- Benchmark / Performance regression check: it's already deleted, but still being executed
- CI / benchmark: can't access `secrets.RV32EMU_BENCH_TOKEN` (I believe after merging the PR this will be resolved, as this is a security feature so we can't leak the secret using a PR from a contributor)

2024-07-10 09:36 UTC, jserv commented
Move the commit "Fix typo and remove outdated comment" out of this pull request.

2024-07-10 09:43 UTC, henrybear327 commented
> Move the commit "Fix typo and remove outdated comment" out of this pull request.

Done as requested (a new PR is created)

2024-07-10 10:00 UTC, henrybear327 commented
> > Move the commit "Fix typo and remove outdated comment" out of this pull request.
> 
> Done as requested (a new PR is created)

Since there are no code changes, the CI pipeline won't be triggered, thus, passing all of them!

2024-07-10 10:20 UTC, merged