Bring wasm service up
sysprog21/rv32emu pull request #487
Opened 2024-09-01 17:11 UTC by ChinYikMing

After merging #474, multiple executables were moved to other locations (e.g., build/riscv32), causing the wasm service to fail. The intuitive solution is to embed build/riscv32 into the wasm.

Additionally, the Makefile's distclean target does not fully clean wasm artifacts, as CC=emcc might not be set during make distclean. To fix this, the declaration of the WEB_FILES and DEMO_DIR wasm-related variables has been reordered.

Related: #486

2024-09-01 17:30 UTC, jserv requested changes
Clarify the git commit message: if this pull request is able to resolve #486, you should write `Close #486` explicitly.

2024-09-01 17:31 UTC, ChinYikMing commented
> Clarify the git commit message: if this pull request is able to resolve #486, you should write `Close #486` explicitly.

I would close #486 if the elf selection list generator is being merged.

2024-09-01 17:34 UTC, ChinYikMing commented
I changed to title in #486.

2024-09-01 20:08 UTC, ChinYikMing commented
Close: #486

2024-09-02 02:16 UTC, jserv commented on mk/wasm.mk
> +	$(Q)tools/gen-elf-list-js.py > $(DEMO_DIR)/elf_list.js
Consider the following:
```shell
$(DEMO_DIR)/elf_list.js: tools/gen-elf-list-js.py
    $(Q)tools/gen-elf-list-js.py > $@
```

2024-09-02 02:27 UTC, jserv requested changes
Rebase the latest `master` branch for passing the architecture tests.

2024-09-02 04:37 UTC, merged

2024-09-02 04:37 UTC, jserv commented
Thank @ChinYikMing for contributing!