Add support of FMIN/MAX
sysprog21/rv32emu pull request #51
Opened 2022-09-08 17:28 UTC by 2011eric

Passed 2 more tests in riscv-arch-test.
Support of fmin and fmax is complete.

2022-09-08 17:55 UTC, jserv commented on riscv_private.h
> +static inline bool is_signan(uint32_t f){
In [Floating-point exceptions](https://www.ibm.com/docs/en/aix/7.3?topic=concepts-floating-point-exceptions) of IBM AIX Manual, signaling NaN is abbreviated as `snan`, which might represent better than "signan." In Linux, the prefix "sig" is used for UNIX signal specific identifiers. However, signaling NaN is quite different from them. Let's name it `is_snan` here.

2022-09-08 17:55 UTC, jserv commented on riscv_private.h
> +static inline bool is_nan(uint32_t f){
Run `clang-format-12 -i *.[ch]` to indent.

2022-09-08 17:59 UTC, jserv requested changes
Rebase the latest "master" branch which checks C/C++ source files for consistent style.

2022-09-08 18:05 UTC, jserv requested changes
You should explain the IEEE754-201x semantics of fmin/fmax in git commit messages.

2022-09-09 01:23 UTC, 2011eric commented
I think I can pack the code into a function, since the code of fmin and the one of fmax is similar.

2022-09-09 03:24 UTC, jserv commented
> I think I can pack the code into a function, since the code of fmin and the one of fmax is similar.

You can introduce some macros as what [SoftFP](https://bellard.org/softfp/) does.

2022-09-10 17:23 UTC, jserv commented
Fix the conflicts caused by recent directory structure changes.

2022-09-11 13:08 UTC, jserv commented on src/riscv_private.h
> +static inline bool is_nan(uint32_t f){
Indent this file as well.

2022-09-11 13:38 UTC, merged