Fix LTO warning by enabling parallel compilation
sysprog21/rv32emu pull request #523
Opened 2024-12-21 07:40 UTC by eleanorLYJ

When using `make`, the following warning occurs:
lto-wrapper: warning: using serial compilation of 2 LTRANS jobs.

To resolve this and enable parallel compilation, -flto=auto is now used. 

According to the [GCC documentation](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html):
Use `-flto=auto` to use GNU make’s job server, if available, or otherwise fall back to autodetection of the number of CPU threads present in your system.

2024-12-21 09:02 UTC, visitorckw approved these changes
Nit: Missing a period in the commit message. Otherwise, LGTM. Thanks!

2024-12-21 18:20 UTC, ChinYikMing commented
The warning remains when using older version of `gcc`. @eleanorLYJ Can you check? (maybe provide some fallback mechanism for older `gcc`)?

Note: I tried gcc-12 or above and the warning are gone.

Compiler:
```
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Log:
```
  CC	build/map.o
  CC	build/utils.o
  CC	build/decode.o
  CC	build/io.o
  CC	build/syscall.o
  CC	build/emulate.o
  CC	build/riscv.o
  CC	build/elf.o
  CC	build/cache.o
  CC	build/mpool.o
  CC	build/main.o
  LD	build/rv32emu
**lto-wrapper: warning: using serial compilation of 2 LTRANS jobs**
[OK]
Checking SHA-1 of prebuilt binaries ... [OK]
Running hello.elf ... [OK]
Running puzzle ... [OK]
Running fcalc ... [OK]
Running pi ... [OK]
```

2024-12-21 18:20 UTC, ChinYikMing requested changes
The warning remains when using older version of `gcc`. @eleanorLYJ Can you check? (maybe provide some fallback mechanism for older `gcc`)

Note: I tried gcc-12 or above and the warning are gone.

Compiler:
```
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Log:
```
  CC	build/map.o
  CC	build/utils.o
  CC	build/decode.o
  CC	build/io.o
  CC	build/syscall.o
  CC	build/emulate.o
  CC	build/riscv.o
  CC	build/elf.o
  CC	build/cache.o
  CC	build/mpool.o
  CC	build/main.o
  LD	build/rv32emu
lto-wrapper: warning: using serial compilation of 2 LTRANS jobs
[OK]
Checking SHA-1 of prebuilt binaries ... [OK]
Running hello.elf ... [OK]
Running puzzle ... [OK]
Running fcalc ... [OK]
Running pi ... [OK]
```

2024-12-22 13:39 UTC, jserv requested changes
Always rebase the latest `master` branch when you submit pull requests.

2024-12-22 19:36 UTC, visitorckw commented
> The warning remains when using older version of `gcc`. @eleanorLYJ Can you check? (maybe provide some fallback mechanism for older `gcc`)
> 
> Note: I tried gcc-12 or above and the warning are gone.
> 

Hmm, that's strange.
Is there a difference in the functionality of -flto=auto between gcc v11.4 and now?
Or does GCC v11.4 not even support the auto parameter?

2024-12-23 06:06 UTC, ChinYikMing commented
> > The warning remains when using older version of `gcc`. @eleanorLYJ Can you check? (maybe provide some fallback mechanism for older `gcc`)
> > Note: I tried gcc-12 or above and the warning are gone.
> 
> Hmm, that's strange. Is there a difference in the functionality of -flto=auto between gcc v11.4 and now? Or does GCC v11.4 not even support the auto parameter?

Found [this](https://stackoverflow.com/questions/72218980/gcc-v12-1-warning-about-serial-compilation) at stackoverflow. The warning is introduced from v11.4 . Thus, I believe it might be specific to version 11.4 or later but below version 12. 

I think we can mention this in the commit message.

2024-12-23 18:03 UTC, ChinYikMing commented
Don't use markdown syntax in the body of git commit messages since not every parser recognizes the format (I meant the gcc docs link here). Instead, always use plaintext. Thanks!

2024-12-23 18:11 UTC, jserv commented
> Don't use markdown syntax in the body of git commit messages since not every parser recognizes the format (I meant the gcc docs link here). Instead, always use plaintext. Thanks!

Change the following:
> According to the [GCC documentation](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html):
Use -flto=auto to use GNU make’s job server, if available, or otherwise
fall back to autodetection of the number of CPU threads present in your
system.

to 
> According to GCC optimization options [1], ...
> [1]  https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html

2024-12-24 18:20 UTC, ChinYikMing approved these changes
LGTM.

2024-12-25 00:22 UTC, merged

2024-12-25 00:22 UTC, jserv commented
Thank @eleanorLYJ for contributing!