Add bitmanip extension support
sysprog21/rv32emu pull request #525
Opened 2024-12-22 16:05 UTC by visitorckw

Add support for the RISC-V bitmanip extensions Zba, Zbb, Zbc, and Zbs. These extensions optimize bitwise operations such as memory addressing, bitfield manipulation, counting leading/trailing zeros, and extracting subfields. All implementations have been validated through architectural tests, ensuring their correctness and reliability in emulating these operations.

2024-12-22 16:12 UTC, jserv reviewed
<!-- github-benchmark-action-comment(start): Benchmarks Summary -->
# Benchmarks

<details>

| Benchmark suite | Current: e7ded18da549393a3e2c96550ac4fadf51bd06ab | Previous: bab4b8e92e7afeff1300fff43fceb792884464a5 | Ratio |
|-|-|-|-|
| `Dhrystone` | `1301` Average DMIPS over 10 runs | `1309` Average DMIPS over 10 runs | `1.01` |
| `Coremark` | `977.65` Average iterations/sec over 10 runs | `953.749` Average iterations/sec over 10 runs | `0.98` |

</details>

This comment was automatically generated by [workflow](https://github.com/sysprog21/rv32emu/actions?query=workflow%3ABenchmark) using [github-action-benchmark](https://github.com/marketplace/actions/continuous-benchmark).
<!-- github-benchmark-action-comment(end): Benchmarks Summary -->

2024-12-23 02:43 UTC, jserv requested changes
Update the top-level `README.md` as well.

2024-12-23 12:56 UTC, ChinYikMing commented on src/decode.c
> +        if ((ir->imm >> 5) == 0b0110000) { /* rori */
Remove bracket for consistency.

2024-12-23 18:03 UTC, merged

2024-12-23 18:04 UTC, jserv commented
Thank @visitorckw for contributing!