Fix crash on system without mmap()
sysprog21/rv32emu pull request #531
Opened 2024-12-28 07:47 UTC by RinHizakura

In the case that `HAVE_MMAP` is 0, the emulator crashes.

```
$ make ENABLE_SYSTEM=1 system
rv32emu: src/emulate.c:626: block_translate: Assertion `insn' failed.
Aborted
```

The `map_file()` logic when `HAVE_MMAP == 0` is weird as it allocates extra resources to the emulated memory, and after this change the aborting issue is gone. I believe the original is not the correct implementation.

2024-12-28 07:52 UTC, RinHizakura commented
I guess that we don't have coverage for `HAVE_MMAP = 0`. Do we need to have it?

2024-12-28 07:54 UTC, jserv reviewed
<!-- github-benchmark-action-comment(start): Benchmarks Summary -->
# Benchmarks

<details>

| Benchmark suite | Current: 0ca9dee2cb8f8e4b7b2602f51f0be34f0304028a | Previous: ecb20c82197edf5429109a3f906d735b2ba687db | Ratio |
|-|-|-|-|
| `Dhrystone` | `1322` Average DMIPS over 10 runs | `1346` Average DMIPS over 10 runs | `1.02` |
| `Coremark` | `958.695` Average iterations/sec over 10 runs | `950.448` Average iterations/sec over 10 runs | `0.99` |

</details>

This comment was automatically generated by [workflow](https://github.com/sysprog21/rv32emu/actions?query=workflow%3ABenchmark) using [github-action-benchmark](https://github.com/marketplace/actions/continuous-benchmark).
<!-- github-benchmark-action-comment(end): Benchmarks Summary -->

2024-12-28 16:11 UTC, vacantron requested changes
Please refine the commit message that might contain "avoid reallocating memory" (or something like that) to indicate your change.

2024-12-28 21:13 UTC, jserv commented
> BTW, I guess that we don't have coverage for `HAVE_MMAP = 0`. Do we need to have it?

The condition `HAVE_MMAP=0` is useful when profiling, as it is not straightforward to measure the system memory consumption when `mmap` is heavily used during emulation.

2024-12-29 12:12 UTC, ChinYikMing commented
@RinHizakura Thanks for the fix. It indeed an implementation bug.

2024-12-29 13:42 UTC, RinHizakura commented
> The condition HAVE_MMAP=0 is useful when profiling, as it is not straightforward to measure the system memory consumption when mmap is heavily used during emulation.

Sorry for the unclear question, I was asking about the CI/CD coverage in fact.

2024-12-30 04:13 UTC, jserv commented
> I was asking about the CI/CD coverage in fact.

You can simply skip the condition `HAVE_MMAP=0` in CI/CD pipeline.

2024-12-30 04:34 UTC, jserv commented
Breakage reported by CI:
```
src/jit.c:1760:17: warning: ‘do_sret’ defined but not used [-Wunused-function]
 1760 |     static void do_##inst(struct jit_state *state UNUSED, riscv_t *rv UNUSED, \
      |                 ^~~
src/rv32_jit.c:355:1: note: in expansion of macro ‘GEN’
  355 | GEN(sret, {assert(NULL);
      | ^~~
```

2024-12-30 04:53 UTC, RinHizakura commented
This is not related to this change. The same warning can be found in other CI/CD jobs https://github.com/sysprog21/rv32emu/actions/runs/12540405349/job/34967656388 even if it passes.

2024-12-30 05:54 UTC, merged

2024-12-30 05:54 UTC, jserv commented
Thank @RinHizakura for contributing!