Add the instruction `c.ebreak`
sysprog21/rv32emu pull request #60
Opened 2022-09-28 22:03 UTC by Risheng1128

This commit adds the instruction `c.ebreak` into rv32emu.

Input the following command, and the `c.ebreak ` test will pass.
> make arch-test RISCV_DEVICE=C

2022-09-29 03:19 UTC, jserv commented on src/emulate.c
> +void rv_except_breakpoint(struct riscv_t *rv)
This function should be marked as `static`.

2022-09-29 03:21 UTC, jserv commented on src/emulate.c
> +void rv_except_breakpoint(struct riscv_t *rv)
For the sake of consistency, the function prototype should be
```c
void rv_except_breakpoint(struct riscv_t *rv, uint32_t insn);
```

2022-09-29 03:22 UTC, jserv requested changes
Change `README.md` to reflect the results of RISC-V Architecture Tests.

2022-09-29 03:26 UTC, jserv commented
Check the article [How to Write a Git Commit Message](https://cbea.ms/git-commit/) to summarize this change.

2022-09-29 18:39 UTC, Risheng1128 commented
For the consistent prototype with other exception handlers. I redeclare the `rv_except_breakpoint`.
```diff
- void rv_except_breakpoint(struct riscv_t *rv)
+ static void rv_except_breakpoint(struct riscv_t *rv, uint32_t old_pc)
```

Add the new function `breakpoint_handler` and change `README.md`.

2022-09-29 22:42 UTC, jserv commented on src/riscv.h
> +void breakpoint_handler(struct riscv_t *rv);
In order to differentiate breakpoints in the GDB stub, rename to `ebreak_handler`.

2022-09-29 22:45 UTC, jserv commented
Check `privilege` item in RISC-V Architecture Tests as well.

2022-09-30 12:38 UTC, Risheng1128 commented
`privilege` instuction test result: 
```shell
Check ebreak                    ... FAIL 
Check ecall                     ... FAIL 
Check misalign1-jalr-01         ... OK 
Check misalign2-jalr-01         ... OK 
Check misalign-beq-01           ... OK 
Check misalign-bge-01           ... OK 
Check misalign-bgeu-01          ... OK 
Check misalign-blt-01           ... OK 
Check misalign-bltu-01          ... OK 
Check misalign-bne-01           ... OK 
Check misalign-jal-01           ... OK 
Check misalign-lh-01            ... OK 
Check misalign-lhu-01           ... OK 
Check misalign-lw-01            ... FAIL 
Check misalign-sh-01            ... OK 
Check misalign-sw-01            ... FAIL
```

2022-09-30 12:41 UTC, jserv commented
> `privilege` instruction test result:
> Check ebreak                    ... FAIL 
> Check ecall                     ... FAIL 

Create a new issue regarding `privilege` instruction regressions.

2022-09-30 13:33 UTC, Risheng1128 commented
Rename the function:
```diff
- void breakpoint_handler(struct riscv_t *rv);
+ void ebreak_handler(struct riscv_t *rv);
```

2022-09-30 13:42 UTC, merged

2022-09-30 13:43 UTC, jserv commented
Thank @Risheng1128 for contributing!