Pass several privilege tests and fix RV32I comment
sysprog21/rv32emu pull request #65
Opened 2022-10-09 20:27 UTC by Risheng1128

This commit do the following things:
- Pass serveral privilege instruction and exceptions tests like ebreak, 
  misaligned load word and misaligned store word.
- Immediately, fix the comment of different type of RV32I instructions 
  format like I, R and J-type and so on.

Because the compiler option `rv32gc` will make `ebreak` be compiled
as `c.ebreak` format, so change it to `rv32g`.

2022-10-09 20:39 UTC, jserv requested changes
Update README.md in top-level directory.

2022-10-09 20:42 UTC, jserv commented
I would anticipate the commit being divided into two:
1. Refine comments for RV32 instruction descriptions.
2. Improve compliance for privileged instructions.

2022-10-10 09:07 UTC, Risheng1128 commented
The privilege tests result:
```shell
Check ebreak                    ... OK 
Check ecall                     ... FAIL 
Check misalign1-jalr-01         ... OK 
Check misalign2-jalr-01         ... OK 
Check misalign-beq-01           ... OK 
Check misalign-bge-01           ... OK 
Check misalign-bgeu-01          ... OK 
Check misalign-blt-01           ... OK 
Check misalign-bltu-01          ... OK 
Check misalign-bne-01           ... OK 
Check misalign-jal-01           ... OK 
Check misalign-lh-01            ... OK 
Check misalign-lhu-01           ... OK 
Check misalign-lw-01            ... OK 
Check misalign-sh-01            ... OK 
Check misalign-sw-01            ... OK 
```

2022-10-10 09:27 UTC, jserv requested changes
Analyze the reason why ecall fails and describe in the git commit message.

2022-10-10 15:20 UTC, Risheng1128 commented
The privilege instruction `ecall` doesn't pass the test because it only
dispatches the syscall number to corresponding handler in current
rv32emu.
Therefore, it needs to implement the exception handler with control
and status registers (CSRs).

2022-10-10 17:26 UTC, merged

2022-10-10 17:26 UTC, jserv commented
Thank @Risheng1128 for contributing!